# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

joint_limits:
  panda_joint1:
    min_position: -2.89
    max_position: 2.89
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint2:
    min_position: -1.76
    max_position: 1.76
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint3:
    min_position: -2.89
    max_position: 2.89
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint4:
    min_position: -3.07
    max_position: -0.07
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint5:
    min_position: -2.89
    max_position: 2.89
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint6:
    min_position: -0.01
    max_position: 3.75
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_joint7:
    min_position: -2.89
    max_position: 2.89
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
  panda_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  panda_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
